apiVersion: v1
kind: Pod
metadata:
  name: samplepod-interface-name
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name" : "ipvlan-conf",
              "interface": "oam" }
    ]'
spec:
  containers:
  - name: samplepod-interface-name
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
