apiVersion: v1
kind: Pod
metadata:
  name: samplepod-http
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-conf@http
spec:
  containers:
  - name: samplepod-http
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
